#!/bin/sh
# Creates the initial Prisma migration from prisma/schema.prisma (Phase 13).
# Run ONCE, review the SQL, and commit prisma/migrations/. Needs no database:
# `prisma migrate diff --from-empty` writes the exact SQL Prisma would apply.
#   npm run db:baseline
set -eu
dir="prisma/migrations/0001_init"
if [ -e "$dir/migration.sql" ]; then
  echo "$dir/migration.sql already exists; nothing to do." >&2
  exit 1
fi
mkdir -p "$dir"
npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script > "$dir/migration.sql"
printf '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "mysql"\n' > prisma/migrations/migration_lock.toml
echo "Wrote $dir/migration.sql ($(grep -c 'CREATE TABLE' "$dir/migration.sql") tables). Review it, then commit prisma/migrations/."
echo "Existing databases created earlier with 'migrate dev' or 'db push': mark it as applied once with"
echo "  npx prisma migrate resolve --applied 0001_init"
