/**
 * Generates src/server/db/unique-keys.generated.ts from prisma/schema.prisma:
 *   tsx scripts/db/gen-unique-keys.ts
 * Run after every schema change (a test fails while the file is out of date).
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseSchema } from "./schema-ddl";

export function uniqueKeysSource(schemaPath: string): string {
  const s = parseSchema(schemaPath);
  const lines = [...s.models.values()].map((m) => {
    const keys: string[][] = [];
    if (m.id.length) keys.push(m.id);
    for (const f of m.fields) if (f.isUnique) keys.push([f.name]);
    keys.push(...m.uniques);
    return `  ${m.name}: [${keys.map((k) => `[${k.map((f) => JSON.stringify(f)).join(", ")}]`).join(", ")}],`;
  });
  return `// GENERATED by scripts/db/gen-unique-keys.ts from prisma/schema.prisma. Do not edit.\nexport const UNIQUE_KEYS: Record<string, readonly (readonly string[])[]> = {\n${lines.join("\n")}\n};\n`;
}

if (process.argv[1]?.endsWith("gen-unique-keys.ts")) {
  const root = join(__dirname, "..", "..");
  writeFileSync(join(root, "src/server/db/unique-keys.generated.ts"), uniqueKeysSource(join(root, "prisma/schema.prisma")));
  console.log("wrote src/server/db/unique-keys.generated.ts");
}
