/**
 * Minimal Prisma-schema parser and DDL generator.
 *
 * Purpose: (1) produce a MySQL DDL *reference* for DBA review, (2) build an
 * identical SQLite database for offline verification of keys, constraints and
 * seed idempotency. The authoritative MySQL migration is still generated by
 * `prisma migrate dev` (Prisma's own naming/checksums); this file is for review
 * and testing, never applied on top of Prisma migrations.
 */
import { readFileSync } from "node:fs";

export type Scalar = "String" | "Int" | "Float" | "Boolean" | "DateTime" | "Json" | "BigInt" | "Bytes";
export interface Field {
  name: string;
  type: string; // scalar, enum or model name
  optional: boolean;
  list: boolean;
  isId: boolean;
  isUnique: boolean;
  isUpdatedAt: boolean;
  default?: { kind: "cuid" | "now" | "autoincrement" | "value"; value?: string };
  dbType?: string; // Text, MediumText, VarChar(255), Date
  relation?: { name?: string; fields: string[]; references: string[]; onDelete?: string };
}
export interface Model {
  name: string;
  fields: Field[];
  id: string[];
  uniques: string[][];
  indexes: string[][];
}
export interface Schema {
  models: Map<string, Model>;
  enums: Map<string, string[]>;
}

const SCALARS = new Set(["String", "Int", "Float", "Boolean", "DateTime", "Json", "BigInt", "Bytes"]);

export function parseSchema(path: string): Schema {
  const src = readFileSync(path, "utf8").replace(/\/\/[^\n]*/g, "");
  const enums = new Map<string, string[]>();
  for (const m of src.matchAll(/enum (\w+) \{([^}]*)\}/g)) enums.set(m[1], m[2].split(/\s+/).filter(Boolean));
  const models = new Map<string, Model>();
  for (const m of src.matchAll(/model (\w+) \{([^}]*)\}/g)) {
    const model: Model = { name: m[1], fields: [], id: [], uniques: [], indexes: [] };
    for (const raw of m[2].split("\n")) {
      const line = raw.trim();
      if (!line) continue;
      const list = (re: RegExp) => (line.match(re)?.[1] ?? "").split(",").map((s) => s.trim()).filter(Boolean);
      if (line.startsWith("@@id")) { model.id = list(/@@id\(\[([^\]]+)\]/); continue; }
      if (line.startsWith("@@unique")) { model.uniques.push(list(/@@unique\(\[([^\]]+)\]/)); continue; }
      if (line.startsWith("@@index")) { model.indexes.push(list(/@@index\(\[([^\]]+)\]/)); continue; }
      const fm = line.match(/^(\w+)\s+(\w+)(\[\])?(\?)?(.*)$/);
      if (!fm) continue;
      const [, name, type, isList, opt, rest] = fm;
      const f: Field = {
        name, type, list: !!isList, optional: !!opt,
        isId: /@id\b/.test(rest), isUnique: /@unique\b/.test(rest), isUpdatedAt: /@updatedAt\b/.test(rest),
      };
      const d = rest.match(/@default\(([^)]*\)?)\)/);
      if (d) {
        const v = d[1];
        f.default = v.startsWith("cuid") ? { kind: "cuid" } : v.startsWith("now") ? { kind: "now" } : v.startsWith("autoincrement") ? { kind: "autoincrement" } : { kind: "value", value: v };
      }
      const db = rest.match(/@db\.(\w+(?:\(\d+\))?)/);
      if (db) f.dbType = db[1];
      const rel = rest.match(/@relation\(([^)]*\][^)]*|[^)]*)\)/);
      if (rel) {
        const r = rel[1];
        const fields = r.match(/fields:\s*\[([^\]]*)\]/)?.[1];
        f.relation = {
          name: r.match(/^"(\w+)"/)?.[1],
          fields: fields ? fields.split(",").map((s) => s.trim()) : [],
          references: (r.match(/references:\s*\[([^\]]*)\]/)?.[1] ?? "").split(",").map((s) => s.trim()).filter(Boolean),
          onDelete: r.match(/onDelete:\s*(\w+)/)?.[1],
        };
      }
      model.fields.push(f);
      if (f.isId) model.id = [f.name];
    }
    models.set(model.name, model);
  }
  return { models, enums };
}

export const isScalarField = (f: Field, s: Schema) => SCALARS.has(f.type) || s.enums.has(f.type);
export const columns = (m: Model, s: Schema) => m.fields.filter((f) => !f.list && isScalarField(f, s));

function mysqlType(f: Field, s: Schema): string {
  if (s.enums.has(f.type)) return `ENUM(${s.enums.get(f.type)!.map((v) => `'${v}'`).join(", ")})`;
  if (f.dbType === "Text") return "TEXT";
  if (f.dbType === "MediumText") return "MEDIUMTEXT";
  if (f.dbType === "Date") return "DATE";
  if (f.dbType?.startsWith("VarChar")) return f.dbType.replace("VarChar", "VARCHAR");
  if (f.dbType === "MediumBlob") return "MEDIUMBLOB";
  if (f.dbType === "LongBlob") return "LONGBLOB";
  return { String: "VARCHAR(191)", Int: "INTEGER", Float: "DOUBLE", Boolean: "BOOLEAN", DateTime: "DATETIME(3)", Json: "JSON", BigInt: "BIGINT", Bytes: "LONGBLOB" }[f.type as Scalar];
}

function sqliteType(f: Field, s: Schema): string {
  if (s.enums.has(f.type)) return "TEXT";
  return { String: "TEXT", Int: "INTEGER", Float: "REAL", Boolean: "INTEGER", DateTime: "TEXT", Json: "TEXT", BigInt: "INTEGER", Bytes: "BLOB" }[f.type as Scalar];
}

export function generateDDL(s: Schema, dialect: "mysql" | "sqlite"): string {
  const q = (n: string) => (dialect === "mysql" ? `\`${n}\`` : `"${n}"`);
  const out: string[] = [];
  const deferredFks: string[] = [];
  for (const m of s.models.values()) {
    const cols = columns(m, s);
    const lines: string[] = [];
    const singleAutoPk = m.id.length === 1 && cols.find((c) => c.name === m.id[0])?.default?.kind === "autoincrement";
    for (const c of cols) {
      let def = `${q(c.name)} ${dialect === "mysql" ? mysqlType(c, s) : sqliteType(c, s)}`;
      if (dialect === "sqlite" && singleAutoPk && c.name === m.id[0]) {
        lines.push(`${q(c.name)} INTEGER PRIMARY KEY AUTOINCREMENT`);
        continue;
      }
      if (!c.optional) def += " NOT NULL";
      if (c.default?.kind === "now") def += dialect === "mysql" ? " DEFAULT CURRENT_TIMESTAMP(3)" : " DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))";
      if (c.default?.kind === "autoincrement" && dialect === "mysql") def += " AUTO_INCREMENT";
      if (c.default?.kind === "value") {
        const v = c.default.value!;
        const lit = v === "true" ? (dialect === "mysql" ? "true" : "1") : v === "false" ? (dialect === "mysql" ? "false" : "0") : /^-?[\d.]+$/.test(v) ? v : `'${v.replace(/"/g, "")}'`;
        def += ` DEFAULT ${lit}`;
      }
      if (dialect === "sqlite" && s.enums.has(c.type)) def += ` CHECK (${q(c.name)} IN (${s.enums.get(c.type)!.map((v) => `'${v}'`).join(", ")}))`;
      lines.push(def);
    }
    if (!(dialect === "sqlite" && singleAutoPk)) lines.push(`PRIMARY KEY (${m.id.map(q).join(", ")})`);
    const uniques = [...cols.filter((c) => c.isUnique).map((c) => [c.name]), ...m.uniques];
    for (const u of uniques) lines.push(`CONSTRAINT ${q(`${m.name}_${u.join("_")}_key`)} UNIQUE (${u.map(q).join(", ")})`);
    for (const f of m.fields.filter((f) => f.relation?.fields.length)) {
      const r = f.relation!;
      const required = r.fields.every((fk) => !cols.find((c) => c.name === fk)?.optional);
      const onDelete = r.onDelete === "Cascade" ? "CASCADE" : r.onDelete === "SetNull" || !required ? "SET NULL" : "RESTRICT";
      const fk = `CONSTRAINT ${q(`${m.name}_${r.fields.join("_")}_fkey`)} FOREIGN KEY (${r.fields.map(q).join(", ")}) REFERENCES ${q(f.type)}(${r.references.map(q).join(", ")}) ON DELETE ${onDelete} ON UPDATE CASCADE`;
      if (dialect === "mysql") deferredFks.push(`ALTER TABLE ${q(m.name)} ADD ${fk};`);
      else lines.push(fk);
    }
    const tableOpts = dialect === "mysql" ? " DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci" : "";
    out.push(`CREATE TABLE ${q(m.name)} (\n  ${lines.join(",\n  ")}\n)${tableOpts};`);
    for (const ix of m.indexes) out.push(`CREATE INDEX ${q(`${m.name}_${ix.join("_")}_idx`)} ON ${q(m.name)}(${ix.map(q).join(", ")});`);
    // MySQL creates FK indexes automatically; SQLite does not, so add them for fair query plans
    if (dialect === "sqlite") {
      const covered = new Set([...m.indexes, ...uniques, m.id].map((cs) => cs[0]));
      for (const f of m.fields.filter((f) => f.relation?.fields.length)) {
        const first = f.relation!.fields[0];
        if (!covered.has(first)) {
          out.push(`CREATE INDEX ${q(`${m.name}_${first}_fk_idx`)} ON ${q(m.name)}(${q(first)});`);
          covered.add(first);
        }
      }
    }
  }
  if (deferredFks.length) out.push("-- Foreign keys (added after all tables exist)\n" + deferredFks.join("\n"));
  return out.join("\n\n") + "\n";
}

/** Order tables so referenced tables are created/filled first (for FK-safe loading). */
export function topoOrder(s: Schema): string[] {
  const deps = new Map<string, Set<string>>();
  for (const m of s.models.values())
    deps.set(m.name, new Set(m.fields.filter((f) => f.relation?.fields.length && f.type !== m.name).map((f) => f.type)));
  const done: string[] = [];
  const visit = (n: string, stack: Set<string>) => {
    if (done.includes(n) || stack.has(n)) return;
    stack.add(n);
    for (const d of deps.get(n) ?? []) visit(d, stack);
    done.push(n);
  };
  for (const n of deps.keys()) visit(n, new Set());
  return done;
}
