import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { ActionForm } from "@/components/admin/action-form";
import { card, field, h2 } from "@/components/admin/styles";
import { getActor, repo, requireActor } from "@/server/auth/next";
import { can } from "@/server/auth/rbac";
import { getQuestion } from "@/server/admin/questions";
import { aiReviewAction, deleteOneQuestionAction, questionStepAction } from "../../actions";
import { QuestionEditor } from "../question-editor";
import { editorOptions } from "../editor-data";
import { MiniAction } from "@/components/admin/mini-action";
import { attachmentNodes } from "@/server/curriculum-map/questions";
import { deletionRequestOf } from "@/server/admin/question-requests";
import { requestDeletionAction } from "../request-actions";

const ACTION_LABEL: Record<string, string> = {
  "question.ai.generate": "Generated by AI", "question.ai.approve": "Approved (AI draft)", "question.ai.reject": "Rejected (AI draft)",
  "question.create": "Created", "question.update": "Edited", "question.submit": "Sent for review", "question.reject": "Sent back", "question.publish": "Published", "question.archive": "Archived", "question.revise": "New version created",
};

export default async function QuestionPage({ params, searchParams }: { params: Promise<{ questionId: string }>; searchParams?: Promise<{ msg?: string }> }) {
  const flash = searchParams ? (await searchParams).msg : undefined;
  const actor = await requireActor({ permission: "questions:read" });
  const me = (await getActor())!.user;
  const { questionId } = await params;
  const d = await getQuestion(repo, actor, questionId).catch(() => null);
  const delReq = d ? await deletionRequestOf((await repo.findUnique("Question", { id: questionId }))!) : null;
  if (!d) notFound();
  const { skills, standards, grades } = await editorOptions(repo, actor.schoolId!);
  const step = (s: string, text: string, opts: { note?: "required" | "optional"; danger?: boolean } = {}) => (
    <ActionForm action={questionStepAction} submit={text} danger={opts.danger} className="space-y-2">
      <input type="hidden" name="questionId" value={d.id} /><input type="hidden" name="step" value={s} />
      {opts.note && <textarea name="note" rows={2} maxLength={1000} required={opts.note === "required"} placeholder={opts.note === "required" ? "What needs to change / why" : "Note (optional)"} className={field} />}
    </ActionForm>
  );
  return (
    <AppShell name={String(me.displayName)}>
      <p><Link href="/admin/questions" className="text-brand-teal hover:underline">← Questions</Link></p>
      <h1 className="mt-2 text-3xl font-bold text-brand-navy">Question <span className="font-mono text-lg text-slate-500">{d.ref}</span></h1>
      <p className="mt-1 text-slate-600">Status: <strong>{d.status.replace("_", " ").toLowerCase()}</strong> · version {d.version}{d.origin === "AI_GENERATED" ? " · AI-drafted" : ""}{d.input.cognitiveLevel ? ` · cognitive level: ${d.input.cognitiveLevel}` : ""}{d.revisionOf ? <> · revision of <Link className="text-brand-teal hover:underline" href={`/admin/questions/${d.revisionOf}`}>the published version</Link></> : null}</p>

      {d.canReviewAi && (
        <section className={card}>
          <h2 className={h2}>Review this AI-drafted question</h2>
          <p className="text-sm text-slate-600">Check the question, the correct answer and the explanation below (edit if needed), then approve it for students or reject it.</p>
          <div className="mt-3 grid gap-4 sm:grid-cols-2">
            <ActionForm action={aiReviewAction} submit="Approve for students" className="space-y-2">
              <input type="hidden" name="questionId" value={d.id} /><input type="hidden" name="decision" value="approve" />
            </ActionForm>
            <ActionForm action={aiReviewAction} submit="Reject" danger className="space-y-2">
              <input type="hidden" name="questionId" value={d.id} /><input type="hidden" name="decision" value="reject" />
              <textarea name="reason" rows={2} required maxLength={500} placeholder="Why is it rejected?" className={field} />
            </ActionForm>
          </div>
        </section>
      )}

      {flash && <p role="status" className="animate-pop mb-4 rounded-2xl bg-teal-50 px-4 py-3 text-teal-900 ring-1 ring-teal-200">{flash}</p>}
      <section className={card}>
        <h2 className={h2}>Next step</h2>
        <div className="mt-3 grid gap-4 sm:grid-cols-2">
          {d.status === "DRAFT" && d.canEdit && step("submit", "Send for review")}
          {d.canReview && step("approve", "Approve and publish", { note: "optional" })}
          {d.canReview && step("reject", "Send back to the author", { note: "required", danger: true })}
          {d.status === "UNDER_REVIEW" && !d.canReview && <p className="text-slate-600">Waiting for a reviewer{d.mine ? " (another person must approve your own question)" : ""}.</p>}
          {d.status === "PUBLISHED" && can(actor, "questions:edit") && step("revise", "Make a new version")}
          {d.status !== "ARCHIVED" && can(actor, "questions:publish") && step("archive", "Archive", { note: "required", danger: true })}
          {(actor.role === "SCHOOL_ADMIN" || actor.role === "SUPER_ADMIN") && can(actor, "questions:publish") && (
            <div className="rounded-xl p-4 ring-1 ring-red-200">
              <p className="font-semibold text-red-800">Delete permanently</p>
              <p className="mt-1 text-sm text-slate-600">Only possible while no student has answered it. Afterwards, archive it instead.</p>
              <div className="mt-2"><MiniAction action={deleteOneQuestionAction} fields={{ questionId: d.id }} label="Delete question" tone="danger" confirm="Delete this question permanently? This cannot be undone." /></div>
            </div>
          )}
          {actor.role === "TEACHER" && d.status !== "ARCHIVED" && (
            <div className="rounded-xl p-4 ring-1 ring-red-200">
              <p className="font-semibold text-red-800">🗑 Request deletion</p>
              {delReq ? <p className="mt-1 text-sm text-slate-700">Requested by {delReq.byName} on {delReq.at.slice(0, 10)}: “{delReq.reason}”. An admin will decide.</p> : (
                <form action={requestDeletionAction} className="mt-2 space-y-2">
                  <input type="hidden" name="questionId" value={d.id} />
                  <textarea name="reason" required minLength={5} maxLength={500} rows={2} placeholder="Why should it be removed?" className="w-full rounded-xl border border-slate-300 px-3 py-2 text-sm" />
                  <button className="rounded-xl bg-red-50 px-4 py-2 text-sm font-semibold text-red-800 ring-1 ring-red-200 hover:bg-red-100">Send the request to the admin</button>
                </form>
              )}
            </div>
          )}
          {delReq && actor.role !== "TEACHER" && <p className="rounded-xl bg-red-50 px-3 py-2 text-sm text-red-800">🗑 Deletion requested by {delReq.byName}: “{delReq.reason}”. <Link href="/admin/questions/requests" className="font-semibold underline">Decide</Link></p>}
          {d.status === "PUBLISHED" && d.canEdit && <p className="text-sm text-slate-600">No student has answered this question yet, so you can edit it directly below. Once students answer it, changes go through “Make a new version”.</p>}
          {d.status === "PUBLISHED" && !d.canEdit && <p className="text-sm text-slate-600">This question has been answered by students (or you cannot edit published questions): its statistics belong to this exact wording. “Make a new version” replaces it when approved.</p>}
        </div>
      </section>

      <section className={card}>
        <h2 className={h2}>{d.canEdit ? "Edit" : "Question"}</h2>
        <div className="mt-3"><QuestionEditor questionId={d.id} initial={d.input} skills={skills} standards={standards} readOnly={!d.canEdit} curriculum={can(actor, "curriculum:edit") ? { grades } : undefined} places={(await attachmentNodes(repo, actor.schoolId!)).map((p) => ({ code: p.code, grade: p.grade, unit: p.unit, path: p.path }))} /></div>
      </section>

      <section className={card}>
        <h2 className={h2}>History</h2>
        <ol className="mt-2 space-y-1 text-sm">
          {d.history.map((h, i) => <li key={i}><span className="text-slate-500">{h.at.slice(0, 16).replace("T", " ")}</span> · {ACTION_LABEL[h.action] ?? h.action} · <bdi>{h.by}</bdi>{h.note ? <> · <em>“{h.note}”</em></> : null}</li>)}
        </ol>
      </section>
    </AppShell>
  );
}
