/**
 * Report language: English or Arabic labels, number and date formatting.
 *
 * Rules
 *  - Only the report's own words are translated. Curriculum content (skill names,
 *    CCSS standard text) stays in English, exactly as in the school's curriculum,
 *    and the Arabic report says so in its notes.
 *  - Dates are Gregorian in both languages. (Intl's default calendar for "ar-SA" is
 *    Umm al-Qura, which would silently change every date, so the calendar is forced.)
 *  - Digits are Western (0-9) by default in both languages, matching MAP RIT scores,
 *    student numbers and the school's spreadsheets. "arab" switches the Arabic
 *    report to Arabic-Indic digits.
 *  - Official values (MAP RIT, percentile) are never reformatted beyond digits.
 */
import type { Period } from "../analytics/periods";

export type Locale = "en" | "ar";
export type Digits = "latn" | "arab";
export const LOCALES: readonly Locale[] = ["en", "ar"];

export const dirOf = (l: Locale): "ltr" | "rtl" => (l === "ar" ? "rtl" : "ltr");

const EN = {
  // titles
  "title.student": "Student Progress Report",
  "title.class": "Class Progress Report",
  "title.standards": "Standards Report",
  "title.school": "School Summary Report",
  subtitle: "English Language Arts · Adaptive Practice",
  // meta
  "meta.student": "Student",
  "meta.studentNumber": "Student number",
  "meta.grade": "Grade",
  "meta.class": "Class",
  "meta.scope": "Scope",
  "meta.period": "Period",
  "meta.generated": "Generated",
  "meta.generatedBy": "Generated by",
  "scope.school": "Whole school",
  // shared
  none: "—",
  noData: "No data for this period.",
  hidden: "Hidden (fewer than 5 students)",
  confidential: "Confidential: student data",
  page: "Page",
  of: "of",
  unit: "Unit",
  // student KPIs
  "kpi.questions": "Questions answered",
  "kpi.accuracy": "Accuracy",
  "kpi.minutes": "Practice time (min)",
  "kpi.sessions": "Practice sessions",
  "kpi.avgSeconds": "Average answer time (sec)",
  "kpi.mastered": "Skills mastered",
  "kpi.developing": "Skills developing",
  "kpi.needSupport": "Skills needing support",
  "kpi.curriculum": "Curriculum progress",
  "kpi.growth": "Mastery growth (points)",
  "kpi.readingRange": "Reading range (internal)",
  // class KPIs
  "kpi.students": "Students",
  "kpi.active": "Active students",
  "kpi.avgMastery": "Average mastery",
  "kpi.skillsMasteredTotal": "Skills mastered (total)",
  "kpi.studentsNeedSupport": "Students needing support",
  "kpi.classes": "Classes",
  // sections
  "sec.summary": "Summary",
  "sec.units": "Progress by unit",
  "sec.skills": "Skills",
  "sec.growth": "Growth this period",
  "sec.domains": "Level by area",
  "sec.map": "Imported MAP Growth results (official)",
  "sec.students": "Students",
  "sec.comparison": "Comparison",
  "sec.external": "External benchmarks",
  "sec.distribution": "Mastery distribution",
  "sec.weak": "Skills to reteach",
  "sec.strong": "Strongest skills",
  "sec.standards": "Accuracy by standard",
  "sec.classes": "Classes",
  "sec.notes": "Notes",
  // columns
  "col.skill": "Skill",
  "col.level": "Level",
  "col.score": "Mastery",
  "col.questions": "Questions",
  "col.accuracy": "Accuracy",
  "col.lastPractised": "Last practised",
  "col.start": "Start",
  "col.now": "Now",
  "col.change": "Change",
  "col.area": "Area",
  "col.testDate": "Test date",
  "col.subject": "Subject",
  "col.goalArea": "Goal area",
  "col.rit": "RIT",
  "col.percentile": "Percentile",
  "col.student": "Student",
  "col.studentNumber": "Student number",
  "col.group": "Group",
  "col.placement": "Placement",
  "col.avgMastery": "Avg mastery",
  "col.skillsMastered": "Skills mastered",
  "col.minutes": "Minutes",
  "col.lastActive": "Last active",
  "col.alerts": "Open alerts",
  "col.comparisonGroup": "Group",
  "col.students": "Students",
  "col.withData": "With data",
  "col.meanGrowth": "Mean growth",
  "col.benchmark": "Benchmark",
  "col.value": "Value",
  "col.source": "Source",
  "col.band": "Band",
  "col.count": "Students",
  "col.standard": "Standard",
  "col.description": "Description",
  "col.answers": "Answers",
  "col.grade": "Grade",
  "col.class": "Class",
  "col.active": "Active",
  "col.needSupport": "Need support",
  // comparison rows
  "cmp.class": "Class {name}",
  "cmp.grade": "Grade {level} (school)",
  "cmp.school": "Whole school",
  "ext.national.none": "National benchmark data not available.",
  "ext.district.none": "District benchmark data not available.",
  "ext.national": "National reference (imported)",
  "ext.district": "District reference (imported)",
  // notes
  "note.internal": "Mastery, accuracy, growth and reading range are internal platform measures. They are not MAP, Lexile or IXL scores.",
  "note.map": "MAP Growth values are shown exactly as imported from the school's NWEA reports and are never converted to or from platform measures.",
  "note.english": "Skill and standard names are shown in English, as in the curriculum.",
  "note.growth": "Growth compares each skill with itself and needs at least two measurements, so newly started skills are not counted.",
  "note.suppressed": "Group averages are hidden when fewer than 5 students have data, to protect privacy.",
  "note.standardsMin": "Standards with fewer than 5 answers are not shown. Standards with no answers yet: {n}.",
  "note.noMap": "No MAP Growth results have been imported for this student.",
  // periods
  "period.LAST_7_DAYS": "Last 7 days",
  "period.LAST_30_DAYS": "Last 30 days",
  "period.firstSemester": "First semester",
  "period.secondSemester": "Second semester",
  "period.last12": "Last 12 months",
  "period.term": "{name}",
  "period.year": "School year {name}",
  "period.custom": "{from} to {to}",
} as const;

export type LabelKey = keyof typeof EN;

const AR: Record<LabelKey, string> = {
  "title.student": "تقرير تقدّم الطالب",
  "title.class": "تقرير تقدّم الشعبة",
  "title.standards": "تقرير المعايير",
  "title.school": "التقرير الملخّص للمدرسة",
  subtitle: "اللغة الإنجليزية · التدريب التكيّفي",
  "meta.student": "الطالب",
  "meta.studentNumber": "الرقم المدرسي",
  "meta.grade": "الصف",
  "meta.class": "الشعبة",
  "meta.scope": "النطاق",
  "meta.period": "الفترة",
  "meta.generated": "تاريخ الإصدار",
  "meta.generatedBy": "أصدره",
  "scope.school": "المدرسة كاملة",
  none: "—",
  noData: "لا توجد بيانات لهذه الفترة.",
  hidden: "محجوب (أقل من 5 طلاب)",
  confidential: "سرّي: بيانات طلاب",
  page: "صفحة",
  of: "من",
  unit: "الوحدة",
  "kpi.questions": "الأسئلة المُجابة",
  "kpi.accuracy": "نسبة الإجابات الصحيحة",
  "kpi.minutes": "وقت التدريب (دقيقة)",
  "kpi.sessions": "جلسات التدريب",
  "kpi.avgSeconds": "متوسط زمن الإجابة (ثانية)",
  "kpi.mastered": "المهارات المُتقَنة",
  "kpi.developing": "مهارات في طور النمو",
  "kpi.needSupport": "مهارات تحتاج إلى دعم",
  "kpi.curriculum": "التقدّم في المنهج",
  "kpi.growth": "النمو في الإتقان (نقطة)",
  "kpi.readingRange": "مستوى القراءة (مقياس داخلي)",
  "kpi.students": "عدد الطلاب",
  "kpi.active": "الطلاب النشطون",
  "kpi.avgMastery": "متوسط الإتقان",
  "kpi.skillsMasteredTotal": "المهارات المُتقَنة (المجموع)",
  "kpi.studentsNeedSupport": "طلاب يحتاجون إلى دعم",
  "kpi.classes": "عدد الشعب",
  "sec.summary": "الملخّص",
  "sec.units": "التقدّم حسب الوحدة",
  "sec.skills": "المهارات",
  "sec.growth": "النمو خلال الفترة",
  "sec.domains": "المستوى حسب المجال",
  "sec.map": "نتائج اختبار MAP Growth المستوردة (رسمية)",
  "sec.students": "الطلاب",
  "sec.comparison": "المقارنة",
  "sec.external": "المقارنات الخارجية",
  "sec.distribution": "توزيع مستويات الإتقان",
  "sec.weak": "مهارات تحتاج إلى إعادة تدريس",
  "sec.strong": "أقوى المهارات",
  "sec.standards": "الدقة حسب المعيار",
  "sec.classes": "الشعب",
  "sec.notes": "ملاحظات",
  "col.skill": "المهارة",
  "col.level": "المستوى",
  "col.score": "الإتقان",
  "col.questions": "الأسئلة",
  "col.accuracy": "الدقة",
  "col.lastPractised": "آخر تدريب",
  "col.start": "البداية",
  "col.now": "الآن",
  "col.change": "التغيّر",
  "col.area": "المجال",
  "col.testDate": "تاريخ الاختبار",
  "col.subject": "المادة",
  "col.goalArea": "مجال الهدف",
  "col.rit": "درجة RIT",
  "col.percentile": "المئين",
  "col.student": "الطالب",
  "col.studentNumber": "الرقم المدرسي",
  "col.group": "المجموعة",
  "col.placement": "تحديد المستوى",
  "col.avgMastery": "متوسط الإتقان",
  "col.skillsMastered": "المهارات المُتقَنة",
  "col.minutes": "الدقائق",
  "col.lastActive": "آخر نشاط",
  "col.alerts": "تنبيهات مفتوحة",
  "col.comparisonGroup": "المجموعة",
  "col.students": "الطلاب",
  "col.withData": "لديهم بيانات",
  "col.meanGrowth": "متوسط النمو",
  "col.benchmark": "المقارنة",
  "col.value": "القيمة",
  "col.source": "المصدر",
  "col.band": "المستوى",
  "col.count": "عدد الطلاب",
  "col.standard": "المعيار",
  "col.description": "الوصف",
  "col.answers": "الإجابات",
  "col.grade": "الصف",
  "col.class": "الشعبة",
  "col.active": "النشطون",
  "col.needSupport": "يحتاجون إلى دعم",
  "cmp.class": "الشعبة {name}",
  "cmp.grade": "الصف {level} (المدرسة)",
  "cmp.school": "المدرسة كاملة",
  "ext.national.none": "بيانات المقارنة الوطنية غير متوفرة.",
  "ext.district.none": "بيانات المقارنة على مستوى المنطقة غير متوفرة.",
  "ext.national": "مرجع وطني (مستورد)",
  "ext.district": "مرجع المنطقة (مستورد)",
  "note.internal": "الإتقان والدقة والنمو ومستوى القراءة مقاييس داخلية في المنصة، وليست درجات MAP أو Lexile أو IXL.",
  "note.map": "تُعرض قيم MAP Growth كما وردت تمامًا في تقارير NWEA المستوردة من المدرسة، ولا تُحوَّل إلى مقاييس المنصة ولا منها.",
  "note.english": "تظهر أسماء المهارات والمعايير باللغة الإنجليزية كما وردت في المنهج.",
  "note.growth": "يُقارَن نمو كل مهارة بمستواها السابق، ويتطلّب قياسين على الأقل، لذلك لا تُحتسب المهارات التي بدأ التدريب عليها حديثًا.",
  "note.suppressed": "تُحجب متوسطات المجموعات التي يقل فيها عدد الطلاب الذين لديهم بيانات عن 5، حفاظًا على الخصوصية.",
  "note.standardsMin": "لا تُعرض المعايير التي لديها أقل من 5 إجابات. عدد المعايير التي لم تُجب عنها أي أسئلة بعد: {n}.",
  "note.noMap": "لم تُستورد أي نتائج لاختبار MAP Growth لهذا الطالب.",
  "period.LAST_7_DAYS": "آخر 7 أيام",
  "period.LAST_30_DAYS": "آخر 30 يومًا",
  "period.firstSemester": "النصف الأول من العام الدراسي",
  "period.secondSemester": "النصف الثاني من العام الدراسي",
  "period.last12": "آخر 12 شهرًا",
  "period.term": "{name}",
  "period.year": "العام الدراسي {name}",
  "period.custom": "من {from} إلى {to}",
};

const DICT: Record<Locale, Record<LabelKey, string>> = { en: EN, ar: AR };

export function t(locale: Locale, key: LabelKey, vars: Record<string, string | number> = {}): string {
  return DICT[locale][key].replace(/\{(\w+)\}/g, (_, k: string) => (k in vars ? String(vars[k]) : `{${k}}`));
}

/** Every key exists in both languages (checked by a test; the type also enforces it). */
export function missingTranslations(): LabelKey[] {
  return (Object.keys(EN) as LabelKey[]).filter((k) => !AR[k] || !AR[k].trim());
}

// ------------------------------------------------------------ domain labels

const BANDS: Record<string, [string, string]> = {
  BEGINNING: ["Beginning", "مبتدئ"],
  DEVELOPING: ["Developing", "في طور النمو"],
  APPROACHING: ["Approaching", "يقترب من الإتقان"],
  PROFICIENT: ["Proficient", "متمكّن"],
  MASTERED: ["Mastered", "متقن"],
};

const GROUPS: Record<string, [string, string]> = {
  Intervention: ["Intervention", "يحتاج إلى تدخّل"],
  Developing: ["Developing", "في طور النمو"],
  "On level": ["On level", "ضمن المستوى"],
  Advanced: ["Advanced", "متقدّم"],
};

const PROFICIENCY: Record<string, string> = {
  "Below grade level": "دون مستوى الصف",
  "Approaching grade level": "يقترب من مستوى الصف",
  "At grade level": "في مستوى الصف",
  "Above grade level": "فوق مستوى الصف",
};

const DOMAINS: Record<string, [string, string]> = {
  READING: ["Reading", "القراءة"],
  VOCABULARY: ["Vocabulary", "المفردات"],
  GRAMMAR: ["Grammar", "القواعد"],
  LANGUAGE: ["Punctuation & capitals", "علامات الترقيم والحروف الكبيرة"],
  WORD_STUDY: ["Spelling & word study", "الإملاء ودراسة الكلمات"],
  WRITING: ["Writing", "الكتابة"],
};

const pick = (l: Locale, pair: [string, string] | undefined, fallback: string) => (pair ? pair[l === "ar" ? 1 : 0] : fallback);

/** Band code (MASTERED) or English band label (Mastered) → localized label. */
export function bandLabel(l: Locale, band: string): string {
  const code = band.toUpperCase();
  return pick(l, BANDS[code], band);
}

export const BAND_ORDER = ["BEGINNING", "DEVELOPING", "APPROACHING", "PROFICIENT", "MASTERED"] as const;

export const groupLabel = (l: Locale, g: string | null) => (g === null ? t(l, "none") : pick(l, GROUPS[g], g));
export const proficiencyText = (l: Locale, p: string | null) => (p === null ? t(l, "none") : l === "ar" ? PROFICIENCY[p] ?? p : p);
export const domainLabel = (l: Locale, code: string) => pick(l, DOMAINS[code], code);
/** The English labels the analytics layer already produces ("Punctuation & capitals"), back to the code. */
export const domainCodeFromLabel = (label: string) => Object.entries(DOMAINS).find(([, v]) => v[0] === label)?.[0] ?? null;

const ORDINALS_AR = ["", "الأول", "الثاني", "الثالث", "الرابع", "الخامس", "السادس", "السابع", "الثامن", "التاسع", "العاشر", "الحادي عشر", "الثاني عشر"];

export function gradeName(l: Locale, level: number): string {
  if (l === "ar") return ORDINALS_AR[level] ? `الصف ${ORDINALS_AR[level]}` : `الصف ${level}`;
  return `Grade ${level}`;
}

// -------------------------------------------------------------- formatting

const intlLocale = (l: Locale, digits: Digits) => (l === "ar" ? `ar-SA-u-ca-gregory-nu-${digits}` : "en-GB-u-ca-gregory");

export interface Fmt {
  locale: Locale;
  digits: Digits;
  num(v: number | null | undefined, maxFraction?: number): string;
  pct(v: number | null | undefined): string;
  signed(v: number | null | undefined): string;
  date(v: Date | string | null | undefined): string;
  dateTime(v: Date): string;
}

export function formatter(locale: Locale, digits: Digits = "latn"): Fmt {
  const loc = intlLocale(locale, locale === "ar" ? digits : "latn");
  const none = t(locale, "none");
  const asDate = (v: Date | string) => (v instanceof Date ? v : new Date(v.length === 10 ? `${v}T00:00:00Z` : v));
  return {
    locale,
    digits,
    num: (v, maxFraction = 1) => (v === null || v === undefined || Number.isNaN(v) ? none : new Intl.NumberFormat(loc, { maximumFractionDigits: maxFraction }).format(v)),
    pct: (v) => (v === null || v === undefined ? none : new Intl.NumberFormat(loc, { style: "percent", maximumFractionDigits: 0 }).format(v / 100)),
    signed: (v) => (v === null || v === undefined ? none : new Intl.NumberFormat(loc, { maximumFractionDigits: 1, signDisplay: "exceptZero" }).format(v)),
    date: (v) => (v === null || v === undefined || v === "" ? none : new Intl.DateTimeFormat(loc, { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(asDate(v))),
    dateTime: (v) => new Intl.DateTimeFormat(loc, { day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "Asia/Riyadh" }).format(v),
  };
}

/**
 * Localized period label. Period.label from the analytics layer is English; this
 * re-derives it from the period's name so Arabic reports never show English periods.
 * Term and year names are the school's own data ("Term 1", "2026-2027") and are kept.
 */
export function periodLabel(l: Locale, p: Period, fmt = formatter(l)): string {
  switch (p.name) {
    case "LAST_7_DAYS":
    case "LAST_30_DAYS":
      return t(l, `period.${p.name}`);
    case "SEMESTER":
      return t(l, p.label === "Second semester" ? "period.secondSemester" : "period.firstSemester");
    case "SCHOOL_YEAR":
      return p.label === "Last 12 months" ? t(l, "period.last12") : t(l, "period.year", { name: p.label });
    case "TERM":
      return /^Last 30 days$/.test(p.label) ? t(l, "period.LAST_30_DAYS") : t(l, "period.term", { name: p.label });
    case "CUSTOM":
      return t(l, "period.custom", { from: fmt.date(p.from), to: fmt.date(p.to) });
  }
}
