/** The plan as a Word-compatible HTML document (.doc): opens and edits in Microsoft Word. Every value escaped. */
import type { PersonalPlan } from "./personal-plan";

const esc = (v: unknown) => String(v ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const TITLE = { BELOW: "Below level", ON: "On level", ABOVE: "Above level" } as const;
const RULE = { BELOW: "below the 41st percentile", ON: "41st–60th percentile", ABOVE: "above the 60th percentile" } as const;

export function personalPlanDoc(p: PersonalPlan): string {
  const subj = p.subject === "READING" ? "Reading" : "Language";
  const goal = (g: PersonalPlan["bands"][number]["goals"][number], i: number) =>
    `<p><b>${i + 1}. ${esc(g.area)}</b>${g.meanRit !== null ? ` <span style="color:#666">(group mean RIT ${g.meanRit})</span>` : ""}${g.result ? `<br><span style="color:#166534">Results (last 28 days): ${g.result.answers ? `${g.result.practiced}/${g.result.students} students practiced · ${g.result.answers} answers · ${g.result.accuracy}% correct${g.result.trend !== null ? ` · trend ${g.result.trend >= 0 ? "+" : ""}${g.result.trend}` : ""}` : "not practiced yet"}</span>` : ""}</p><ul>${g.skills.map((k) => `<li>${k.standards.length ? `<b>CCSS.ELA-LITERACY.${esc(k.standards.join(", "))}</b> – ` : ""}${esc(k.name)}</li>`).join("") || "<li>Skills will appear when the area’s skills have questions.</li>"}</ul>`;
  const band = (b: PersonalPlan["bands"][number]) => `
    <h2 style="color:#1F3A68;border-bottom:2px solid #1F3A68">${TITLE[b.band]} ${b.ritRange ? `{${esc(b.ritRange)}}` : ""} <span style="font-size:11pt;color:#666">— ${RULE[b.band]}</span></h2>
    <table border="1" cellspacing="0" cellpadding="4" style="border-collapse:collapse;width:100%"><tr style="background:#1F3A68;color:#fff"><th>Names</th><th>RIT Score</th><th>Projected Spring RIT Score</th><th>Percentile</th></tr>
    ${b.students.map((st) => `<tr><td>${esc(st.name)}${st.rapidGuess !== null && st.rapidGuess >= 30 ? " ⚠️ retest" : ""}</td><td>${st.rit}</td><td>${st.projection ?? ""}</td><td>${st.percentile ?? ""}</td></tr>`).join("") || `<tr><td colspan="4">No students in this group.</td></tr>`}</table>
    <h3>Academic Goals – ${subj} + Standards</h3>${b.goals.map(goal).join("")}
    ${b.strengths.length ? `<h3>Areas of Strength</h3>${b.strengths.map(goal).join("")}` : ""}
    <h3>Resources</h3><ul>${b.resources.map((r) => `<li>${esc(r)}</li>`).join("")}</ul>
    <h3>Progress Monitoring</h3><ul>${b.monitoring.map((r) => `<li>${esc(r)}</li>`).join("")}</ul>`;
  return `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><title>Personalized Plan</title>
<style>body{font-family:Calibri,Arial,sans-serif;font-size:11pt} h1{color:#1F3A68} h3{color:#2b3f8f;margin-bottom:2pt}</style></head><body>
<h1>Personalized Plan – Grade ${esc(p.className)} – ${subj}</h1>
<p><b>Grade:</b> ${esc(p.className)} &nbsp;&nbsp; <b>Subject:</b> L.A (${subj}) &nbsp;&nbsp; <b>Teacher:</b> ${esc(p.teacher)} &nbsp;&nbsp; <b>MAP term:</b> ${esc(p.term ?? "—")}</p>
${p.bands.map(band).join("")}
${p.notTested.length ? `<h3>Not tested yet (${subj})</h3><p>${esc(p.notTested.join(", "))}</p>` : ""}
<p style="color:#666;font-size:9pt">Groups by NWEA achievement percentile (one rule for every class). Goals = the group’s weakest MAP goal areas. Generated by the Al-Anjal platform.</p>
</body></html>`;
}
